anguage: node_js

node_js:
   - node # will use latest node

before_script: # commands to run before the build step
   - npm install -g --silent @angular/cli

script: # the build step
   - ng build --prod

notifications:
  email: mariana@bsi.ufla.br 
    on_failure: change
    on_success: change   